[package]
name = "bigarray"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rocksdb = "0.20.1"
serde_json = "1.0.94"
v8 = "0.66.0"
